export * from '../simple-layout/blog/blog.component'
export * from '../simple-layout/contact-us/contact-us.component'
export * from '../simple-layout/salons/salons.component'
export * from '../simple-layout/home/home.component'
export * from '../simple-layout/blog-details/blog-details.component'