export * from '../directives/blog-list/blog-list.component'
export * from '../shared/header/header.component'
export * from '../shared/footer/footer.component'
export * from '../directives/join-us-now/join-us-now.component'
export * from '../directives/salons-list/salons-list.component'