export * from './more.component';
export * from './settings/settings.component';
export * from './transaction-list/transaction-list.component';
export * from './review-rating/review-rating.component';
export * from './rate-salon/rate-salon.component';
export * from './edit-saloon-profile/edit-saloon-profile.component';
export * from './about/about.component';
export * from './contact-us/contact-us.component';
export * from './privacy-policy/privacy-policy.component';
export * from './schedules/schedules.component';
export * from './terms-condition/terms-condition.component';
export * from './favorite-saloons-list/favorite-saloons-list.component';
export * from './service/service.component';
export * from './employee-list/employee-list.component'